apiVersion: v1
kind: Pod
metadata:
  annotations:
    buildUrl: http://10.0.0.11:32000/job/pipeline01/78/
    cni.projectcalico.org/containerID: 4a5a825ba00bd962720b2db0e100194c03f22e53ecbb66e06bb07800bbb7f7ba
    cni.projectcalico.org/podIP: 172.16.87.219/32
    cni.projectcalico.org/podIPs: 172.16.87.219/32
    runUrl: job/pipeline01/78/
  creationTimestamp: "2023-08-11T03:12:45Z"
  labels:
    jenkins/label: pipeline01_78-r2p7w
    jenkins/label-digest: 388d4fa6edb4b92c7b42305e18be33594533c7a1
    name: jenkins-slave
  name: pipeline01-78-r2p7w-28rkq-ntw7v
  namespace: devops-tools
  resourceVersion: "149364"
  uid: fe300659-e239-41a1-8918-4bcd383e4292
spec:
  containers:
  - args:
    - "99999"
    command:
    - sleep
    image: jpetazzo/dind
    imagePullPolicy: IfNotPresent
    name: jenkins-slave
    resources: {}
    securityContext:
      privileged: true
      runAsGroup: 1000
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/jenkins/
      name: workspace-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-225cq
      readOnly: true
    workingDir: /home/jenkins/
  - env:
    - name: JENKINS_SECRET
      value: 5182f217c8e615fd9810043629954a4bb9ee7814af4b2f5920ecec4823fbe84c
    - name: JENKINS_TUNNEL
      value: 10.0.0.11:31945
    - name: JENKINS_AGENT_NAME
      value: pipeline01-78-r2p7w-28rkq-ntw7v
    - name: JENKINS_NAME
      value: pipeline01-78-r2p7w-28rkq-ntw7v
    - name: JENKINS_AGENT_WORKDIR
      value: /home/jenkins/agent
    - name: JENKINS_URL
      value: http://10.0.0.11:32000/
    image: jenkins/inbound-agent:3131.vf2b_b_798b_ce99-2
    imagePullPolicy: IfNotPresent
    name: jnlp
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-225cq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-node01
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  serviceAccount: jenkins-admin
  serviceAccountName: jenkins-admin
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: workspace-volume
  - name: kube-api-access-225cq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-11T03:12:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-11T03:12:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-11T03:12:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-11T03:12:45Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://18f8e67004e11171a64334c8d9e5210c296fd5a8b45dd6e852c0fdd6d8829d06
    image: docker.io/jpetazzo/dind:latest
    imageID: docker.io/jpetazzo/dind@sha256:f48a1bbf379afdb7a7685abd0130ccd2f214662b086eb7320c296ee83fc6448e
    lastState: {}
    name: jenkins-slave
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-08-11T03:12:47Z"
  - containerID: cri-o://fbeb635c07b9c8d8e6ed8f3706d822c3b803e8d18e3391e31c7207a47a45d2e3
    image: docker.io/jenkins/inbound-agent:3131.vf2b_b_798b_ce99-2
    imageID: docker.io/jenkins/inbound-agent@sha256:663103245845ebf133e6fa104f10593690ed434011c0549d7746bc686683269a
    lastState: {}
    name: jnlp
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-08-11T03:12:47Z"
  hostIP: 10.0.0.11
  phase: Running
  podIP: 172.16.87.219
  podIPs:
  - ip: 172.16.87.219
  qosClass: Burstable
  startTime: "2023-08-11T03:12:46Z"
