apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
  name: agent-orange
  namespace: devops-tools
spec:
  containers:
    - name: docker
      image: docker:24
      command: ["sleep", "999999"]
      tty: true
      securityContext:
        privileged: True
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: m2
      hostPath:
        path: /root/.m2