def dockerRegistry = 'https://registry.hub.docker.com'

pipeline {

  environment {
    dockerImageName = "rpmacaspac/projectcicd"

    projectDir = "workspaces/"
  }
  agent {
    kubernetes {

        yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              labels:
                jenkins: slave
              namespace: devops-tools

            spec:
              containers:
              - args:
                - cat
                command:
                - /bin/sh
                - -c
                image: woozymasta/kaniko-tools
                name: jenkins-slave
                securityContext:
                  runAsGroup: 1000
                  runAsUser: 1000
                volumeMounts:
                - mountPath: /home/jenkins/agent
                  name: workspace-volume
              volumes:
              - emptyDir: {}
                name: workspace-volume 
      '''
    }
  }

  stages {

    // stage('Checkout Source') {
    //   steps {
    //     git 'https://github.com/rpmacaspac/projectcicd.git'
    //   }
    // }

  stage('Build image') {
    steps{
      container('jenkins-slave'){
        script {
            dockerImage = docker.build(dockerImageName)
        }
 //     echo "Hello World"
      }
    }
  }

    stage('Pushing Image') {
      environment {
               registryCredential = 'dockerhublogin'
           }
      steps{
        script {
          docker.withRegistry("${dockerRegistry}" , registryCredential ) {
            dockerImage.push("latest")
          }
        }
      }
    }

    stage('Deploying App to Kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "deploymentservice.yml", kubeconfigId: "kubernetes")
        }
      }
    }

  }

}
