kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-slave
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-slave
  namespace: jenkins

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tLyI6eyJ1c2VybmFtZSI6InJwbWFjYXNwYWMiLCJwYXNzd29yZCI6ImRvY2tlcmh1YiIsImVtYWlsIjoicm9sZW1tYWNhc3BhY0B5YWhvby5jb20iLCJhdXRoIjoiY25CdFlXTmhjM0JoWXpwa2IyTnJaWEpvZFdJPSJ9fX0=  
kind: Secret
metadata:
  name: dockercreds
  namespace: jenkins
type: kubernetes.io/dockerconfigjson

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-slave
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-slave
subjects:
- kind: ServiceAccount
  name: jenkins-slave